In [1]:
import numpy as np 
import pandas as pd

In [2]:
# define the dataframe columns
df=pd.read_html("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")[0]

The dataframe will consist of three columns: PostalCode, Borough, and Neighborhood

In [3]:
df.columns=['Postcode','Borough','Neighbourhood']

df.drop([0],axis=0,inplace=True)

df.reset_index()

,index,Postcode,Borough,Neighbourhood
0,1,M2A,Not assigned,Not assigned
1,2,M3A,North York,Parkwoods
2,3,M4A,North York,Victoria Village
3,4,M5A,Downtown Toronto,Harbourfront
4,5,M5A,Downtown Toronto,Regent Park
5,6,M6A,North York,Lawrence Heights
6,7,M6A,North York,Lawrence Manor
7,8,M7A,Queen's Park,Not assigned
8,9,M8A,Not assigned,Not assigned
9,10,M9A,Etobicoke,Islington Avenue
10,11,M1B,Scarborough,Rouge
11,12,M1B,Scarborough,Malvern
12,13,M2B,Not assigned,Not assigned
13,14,M3B,North York,Don Mills North
14,15,M4B,East York,Woodbine Gardens
15,16,M4B,East York,Parkview Hill
16,17,M5B,Downtown Toronto,Ryerson
17,18,M5B,Downtown Toronto,Garden District
18,19,M6B,North York,Glencairn
19,20,M7B,Not assigned,Not assigned
20,21,M8B,Not assigned,Not assigned
21,22,M9B,Etobicoke,Cloverdale
22,23,M9B,Etobicoke,Islington
23,24,M9B,Etobicoke,Martin Grove
24,25,M9B,Etobicoke,Princess Gardens
25,26,M9B,Etobicoke,West Deane Park
26,27,M1C,Scarborough,Highland Creek
27,28,M1C,Scarborough,Rouge Hill
28,29,M1C,Scarborough,Port Union
29,30,M2C,Not assigned,Not assigned
...,...,...,...,...
257,258,M9X,Not assigned,Not assigned
258,259,M1Y,Not assigned,Not assigned
259,260,M2Y,Not assigned,Not assigned
260,261,M3Y,Not assigned,Not assigned
261,262,M4Y,Downtown Toronto,Church and Wellesley
262,263,M5Y,Not assigned,Not assigned
263,264,M6Y,Not assigned,Not assigned
264,265,M7Y,East Toronto,Business Reply Mail Processing Centre 969 Eastern
265,266,M8Y,Etobicoke,Humber Bay
266,267,M8Y,Etobicoke,King's Mill Park
267,268,M8Y,Etobicoke,Kingsway Park South East
268,269,M8Y,Etobicoke,Mimico NE
269,270,M8Y,Etobicoke,Old Mill South
270,271,M8Y,Etobicoke,The Queensway East
271,272,M8Y,Etobicoke,Royal York South East
272,273,M8Y,Etobicoke,Sunnylea
273,274,M9Y,Not assigned,Not assigned
274,275,M1Z,Not assigned,Not assigned
275,276,M2Z,Not assigned,Not assigned
276,277,M3Z,Not assigned,Not assigned
277,278,M4Z,Not assigned,Not assigned
278,279,M5Z,Not assigned,Not assigned
279,280,M6Z,Not assigned,Not assigned
280,281,M7Z,Not assigned,Not assigned
281,282,M8Z,Etobicoke,Kingsway Park South West
282,283,M8Z,Etobicoke,Mimico NW
283,284,M8Z,Etobicoke,The Queensway West
284,285,M8Z,Etobicoke,Royal York South West
285,286,M8Z,Etobicoke,South of Bloor
286,287,M9Z,Not assigned,Not assigned

 Ignore cells with a borough that is Not assigned.

In [4]:
df.drop(df[df['Borough']=="Not assigned"].index,axis=0, inplace=True)

combined the two nigeighborhood with the same postal address into one row with the neighborhoods

In [5]:
df1=df.groupby("Postcode").agg(lambda x:','.join(set(x)))

If a cell has a borough but a Not assigned neighborhood, then the neighborhood will be the same as the borough.

In [6]:
df1.loc[df1['Neighbourhood']=="Not assigned",'Neighbourhood']=df1.loc[df1['Neighbourhood']=="Not assigned",'Borough']

use the .shape method to print the number of rows of your dataframe.

In [7]:
df1.shape

(103, 2)

In [8]:
df1.head(11)

              Borough                                      Neighbourhood
Postcode
M1B       Scarborough                                      Rouge,Malvern
M1C       Scarborough               Highland Creek,Port Union,Rouge Hill
M1E       Scarborough                    West Hill,Morningside,Guildwood
M1G       Scarborough                                             Woburn
M1H       Scarborough                                          Cedarbrae
M1J       Scarborough                                Scarborough Village
M1K       Scarborough          Kennedy Park,Ionview,East Birchmount Park
M1L       Scarborough                      Oakridge,Golden Mile,Clairlea
M1M       Scarborough      Scarborough Village West,Cliffcrest,Cliffside
M1N       Scarborough                         Birch Cliff,Cliffside West
M1P       Scarborough  Dorset Park,Wexford Heights,Scarborough Town C...

Now add the columns

In [9]:
df_csv = pd.read_csv('http://cocl.us/Geospatial_data')
df_csv.head(5)
df_csv.columns

Index(['Postal Code', 'Latitude', 'Longitude'], dtype='object')

In [10]:
df_csv.columns=['Postcode','Latitude','Longitude']

df_csv.drop([0],axis=0,inplace=True)

df_csv.reset_index()

     index Postcode   Latitude  Longitude
0        1      M1C  43.784535 -79.160497
1        2      M1E  43.763573 -79.188711
2        3      M1G  43.770992 -79.216917
3        4      M1H  43.773136 -79.239476
4        5      M1J  43.744734 -79.239476
5        6      M1K  43.727929 -79.262029
6        7      M1L  43.711112 -79.284577
7        8      M1M  43.716316 -79.239476
8        9      M1N  43.692657 -79.264848
9       10      M1P  43.757410 -79.273304
10      11      M1R  43.750072 -79.295849
11      12      M1S  43.794200 -79.262029
12      13      M1T  43.781638 -79.304302
13      14      M1V  43.815252 -79.284577
14      15      M1W  43.799525 -79.318389
15      16      M1X  43.836125 -79.205636
16      17      M2H  43.803762 -79.363452
17      18      M2J  43.778517 -79.346556
18      19      M2K  43.786947 -79.385975
19      20      M2L  43.757490 -79.374714
20      21      M2M  43.789053 -79.408493
21      22      M2N  43.770120 -79.408493
22      23      M2P  43.752758 -79.400049
23      24      M2R  43.782736 -79.442259
24      25      M3A  43.753259 -79.329656
25      26      M3B  43.745906 -79.352188
26      27      M3C  43.725900 -79.340923
27      28      M3H  43.754328 -79.442259
28      29      M3J  43.767980 -79.487262
29      30      M3K  43.737473 -79.464763
..     ...      ...        ...        ...
72      73      M6C  43.693781 -79.428191
73      74      M6E  43.689026 -79.453512
74      75      M6G  43.669542 -79.422564
75      76      M6H  43.669005 -79.442259
76      77      M6J  43.647927 -79.419750
77      78      M6K  43.636847 -79.428191
78      79      M6L  43.713756 -79.490074
79      80      M6M  43.691116 -79.476013
80      81      M6N  43.673185 -79.487262
81      82      M6P  43.661608 -79.464763
82      83      M6R  43.648960 -79.456325
83      84      M6S  43.651571 -79.484450
84      85      M7A  43.662301 -79.389494
85      86      M7R  43.636966 -79.615819
86      87      M7Y  43.662744 -79.321558
87      88      M8V  43.605647 -79.501321
88      89      M8W  43.602414 -79.543484
89      90      M8X  43.653654 -79.506944
90      91      M8Y  43.636258 -79.498509
91      92      M8Z  43.628841 -79.520999
92      93      M9A  43.667856 -79.532242
93      94      M9B  43.650943 -79.554724
94      95      M9C  43.643515 -79.577201
95      96      M9L  43.756303 -79.565963
96      97      M9M  43.724766 -79.532242
97      98      M9N  43.706876 -79.518188
98      99      M9P  43.696319 -79.532242
99     100      M9R  43.688905 -79.554724
100    101      M9V  43.739416 -79.588437
101    102      M9W  43.706748 -79.594054

[102 rows x 4 columns]

In [11]:
df_csv.rename(index=str, columns={"Postal Code": "Postcode"})

    Postcode   Latitude  Longitude
1        M1C  43.784535 -79.160497
2        M1E  43.763573 -79.188711
3        M1G  43.770992 -79.216917
4        M1H  43.773136 -79.239476
5        M1J  43.744734 -79.239476
6        M1K  43.727929 -79.262029
7        M1L  43.711112 -79.284577
8        M1M  43.716316 -79.239476
9        M1N  43.692657 -79.264848
10       M1P  43.757410 -79.273304
11       M1R  43.750072 -79.295849
12       M1S  43.794200 -79.262029
13       M1T  43.781638 -79.304302
14       M1V  43.815252 -79.284577
15       M1W  43.799525 -79.318389
16       M1X  43.836125 -79.205636
17       M2H  43.803762 -79.363452
18       M2J  43.778517 -79.346556
19       M2K  43.786947 -79.385975
20       M2L  43.757490 -79.374714
21       M2M  43.789053 -79.408493
22       M2N  43.770120 -79.408493
23       M2P  43.752758 -79.400049
24       M2R  43.782736 -79.442259
25       M3A  43.753259 -79.329656
26       M3B  43.745906 -79.352188
27       M3C  43.725900 -79.340923
28       M3H  43.754328 -79.442259
29       M3J  43.767980 -79.487262
30       M3K  43.737473 -79.464763
..       ...        ...        ...
73       M6C  43.693781 -79.428191
74       M6E  43.689026 -79.453512
75       M6G  43.669542 -79.422564
76       M6H  43.669005 -79.442259
77       M6J  43.647927 -79.419750
78       M6K  43.636847 -79.428191
79       M6L  43.713756 -79.490074
80       M6M  43.691116 -79.476013
81       M6N  43.673185 -79.487262
82       M6P  43.661608 -79.464763
83       M6R  43.648960 -79.456325
84       M6S  43.651571 -79.484450
85       M7A  43.662301 -79.389494
86       M7R  43.636966 -79.615819
87       M7Y  43.662744 -79.321558
88       M8V  43.605647 -79.501321
89       M8W  43.602414 -79.543484
90       M8X  43.653654 -79.506944
91       M8Y  43.636258 -79.498509
92       M8Z  43.628841 -79.520999
93       M9A  43.667856 -79.532242
94       M9B  43.650943 -79.554724
95       M9C  43.643515 -79.577201
96       M9L  43.756303 -79.565963
97       M9M  43.724766 -79.532242
98       M9N  43.706876 -79.518188
99       M9P  43.696319 -79.532242
100      M9R  43.688905 -79.554724
101      M9V  43.739416 -79.588437
102      M9W  43.706748 -79.594054

[102 rows x 3 columns]

In [15]:
result = pd.merge(df1,
                 df_csv[['Postcode', 'Latitude', 'Longitude']], on="Postcode")
result.head(11)

,Postcode,Borough,Neighbourhood,Latitude,Longitude
0,M1C,Scarborough,"Highland Creek,Port Union,Rouge Hill",43.784535,-79.160497
1,M1E,Scarborough,"West Hill,Morningside,Guildwood",43.763573,-79.188711
2,M1G,Scarborough,Woburn,43.770992,-79.216917
3,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
4,M1J,Scarborough,Scarborough Village,43.744734,-79.239476
5,M1K,Scarborough,"Kennedy Park,Ionview,East Birchmount Park",43.727929,-79.262029
6,M1L,Scarborough,"Oakridge,Golden Mile,Clairlea",43.711112,-79.284577
7,M1M,Scarborough,"Scarborough Village West,Cliffcrest,Cliffside",43.716316,-79.239476
8,M1N,Scarborough,"Birch Cliff,Cliffside West",43.692657,-79.264848
9,M1P,Scarborough,"Dorset Park,Wexford Heights,Scarborough Town C...",43.757410,-79.273304
10,M1R,Scarborough,"Maryvale,Wexford",43.750072,-79.295849